name: Docker image push demo

on:   
  push:
    branches:
      - main
  pull_request:
  
env:
  IMAGE_NAME: publish_package_demo
  
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build . --file ./sample-packages/docker/Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
